# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('date_payment', models.DateField(null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
